version: '3.7'

# include:
#   - path:
#     - rag_service/docker-compose.yaml


services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  gpt-4-mini:
    build: ./inference_service
    container_name: inference_service_gpt4mini
    ports:
      - "8002:8000"
    environment:
      OPENAI_API_KEY: sk-3IqehGd2A8iAldf9VgG2CgHyGQtO9qPH #${OPENAI_API_KEY}
      MODEL_NAME: "gpt-4o-mini"
      BASE_URL: "https://api.proxyapi.ru/openai/v1"

  gpt-4o:
    build: ./inference_service
    container_name: inference_service_gpt4o
    ports:
      - "8003:8000" # forwards 8003 local port to 8000 container port
    environment:
      OPENAI_API_KEY: sk-3IqehGd2A8iAldf9VgG2CgHyGQtO9qPH #${OPENAI_API_KEY}
      MODEL_NAME: "gpt-4o"
      BASE_URL: "https://api.proxyapi.ru/openai/v1"


  llama3-70b-instruct:
    build: ./inference_service
    container_name: inference_service_llama3_70b
    ports:
      - "8004:8000" 
    environment:
      OPENAI_API_KEY: eyJhbGciOiJIUzI1NiIsImtpZCI6IlV6SXJWd1h0dnprLVRvdzlLZWstc0M1akptWXBvX1VaVkxUZlpnMDRlOFUiLCJ0eXAiOiJKV1QifQ.eyJzdWIiOiJnb29nbGUtb2F1dGgyfDEwNjQ4NDg2MTk5OTM2MjczNjIzOSIsInNjb3BlIjoib3BlbmlkIG9mZmxpbmVfYWNjZXNzIiwiaXNzIjoiYXBpX2tleV9pc3N1ZXIiLCJhdWQiOlsiaHR0cHM6Ly9uZWJpdXMtaW5mZXJlbmNlLmV1LmF1dGgwLmNvbS9hcGkvdjIvIl0sImV4cCI6MTg4ODIyNjIzMCwidXVpZCI6IjlkNmE3NGU1LWM0MmItNGFlYy05ZGMyLTExZTY3NmRkZDZmMSIsIm5hbWUiOiJBSSZEVCBjb3VyY2UiLCJleHBpcmVzX2F0IjoiMjAyOS0xMS0wMVQxMToxNzoxMCswMDAwIn0.WAYpQB5orr96I9XVRlV2g-OWqDcfTCENCDNSKqE575Y #${OPENAI_API_KEY}
      MODEL_NAME: "meta-llama/Meta-Llama-3.1-70B-Instruct"
      BASE_URL: "https://api.studio.nebius.ai/v1/"

  
  mixtral-8x22b-instruct:
    build: ./inference_service
    container_name: inference_service_mixtral_8x22
    ports:
      - "8005:8000" 
    environment:
      OPENAI_API_KEY: eyJhbGciOiJIUzI1NiIsImtpZCI6IlV6SXJWd1h0dnprLVRvdzlLZWstc0M1akptWXBvX1VaVkxUZlpnMDRlOFUiLCJ0eXAiOiJKV1QifQ.eyJzdWIiOiJnb29nbGUtb2F1dGgyfDEwNjQ4NDg2MTk5OTM2MjczNjIzOSIsInNjb3BlIjoib3BlbmlkIG9mZmxpbmVfYWNjZXNzIiwiaXNzIjoiYXBpX2tleV9pc3N1ZXIiLCJhdWQiOlsiaHR0cHM6Ly9uZWJpdXMtaW5mZXJlbmNlLmV1LmF1dGgwLmNvbS9hcGkvdjIvIl0sImV4cCI6MTg4ODIyNjIzMCwidXVpZCI6IjlkNmE3NGU1LWM0MmItNGFlYy05ZGMyLTExZTY3NmRkZDZmMSIsIm5hbWUiOiJBSSZEVCBjb3VyY2UiLCJleHBpcmVzX2F0IjoiMjAyOS0xMS0wMVQxMToxNzoxMCswMDAwIn0.WAYpQB5orr96I9XVRlV2g-OWqDcfTCENCDNSKqE575Y #${OPENAI_API_KEY}
      MODEL_NAME: "mistralai/Mixtral-8x22B-Instruct-v0.1"
      BASE_URL: "https://api.studio.nebius.ai/v1/"


  gateway_service:
    build: ./gateway_service
    container_name: gateway_service
    ports:
      - "8001:8001"
    depends_on:
      - redis
      - gpt-4-mini
      - gpt-4o
      - llama3-70b-instruct
      - mixtral-8x22b-instruct
      - postgres
      - rag_service
    environment:
      ADMIN_KEY: aYpVtQxRmGzLsBnCfDiKjUxWqHvNwYcFbXlPrVdTw #${ADMIN_KEY}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password # changed password in init_script.sql
      POSTGRES_DB: users # name of table. DO NOT CHANGE!

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password # changed password in init_script.sql
      POSTGRES_DB: users # name of table. DO NOT CHANGE!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

  rag_gradio_service:
    build: ./rag_gradio_service
    container_name: rag_gradio_service
    ports:
      - "7860:7860"

volumes:
  postgres_data:
    driver: local
