apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
spec:
  selector:
    matchLabels:
      app: gateway-service
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
      - name: gateway-service
        image: gcr.io/optimum-airfoil-432321-n4/gateway-service:367ab838b0e87d5c0d959ca4791cbaf1480147ad
        ports:
        - containerPort: 8001
        env:
        - name: ADMIN_KEY
          valueFrom:
            secretKeyRef:
              name: gateway-creds
              key: ADMIN_KEY
        - name: REDIS_HOST
          value: "redis"
        - name: INFERENCE_SERVICE_HOST
          value: "gpt-4-mini"
        - name: POSTGRES_HOST
          value: "postgres"
        resources:
          requests:
            cpu: "10m"
          limits:
            cpu: "20m"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001