apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpt-4-mini
spec:
  selector:
    matchLabels:
      app: gpt-4-mini
  replicas: 1
  template:
    metadata:
      labels:
        app: gpt-4-mini
    spec:
      containers:
      - name: gpt-4-mini
        image: gcr.io/optimum-airfoil-432321-n4/inference-service:1
        ports:
        - containerPort: 8000
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-api-key
              key: OPENAI_API_KEY
        - name: MODEL_NAME
          value: "gpt-4-mini"
---
apiVersion: v1
kind: Service
metadata:
  name: gpt-4-mini
spec:
  selector:
    app: gpt-4-mini
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000